apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fronend-bad
  namespace: service-a
spec:
  dnsNames:
  - frontend.service-b
  duration: 10h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: vault
  renewBefore: 5h0m0s
  secretName: frontend-bad-tls
  usages:
  - server auth
  - client auth
