apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: service-b
  namespace: service-a
spec:
  dnsNames:
  - service-b.service-b
  duration: 10h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: vault
  renewBefore: 5h0m0s
  secretName: service-b-tls
  usages:
  - server auth
