apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: service-a
spec:
  dnsNames:
  - frontend.service-a
  duration: 10h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: vault
  renewBefore: 5h0m0s
  secretName: frontend-tls
  usages:
  - server auth
  - client auth
