apiVersion: v1
kind: Namespace
metadata:
  name: service-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-b
---
apiVersion: v1
kind: Service
metadata:
  name: knet-stress
  namespace: service-a
  labels:
    app: knet-stress
spec:
  selector:
    app: knet-stress
  ports:
    - protocol: TCP
      name: web
      port: 6443
      targetPort: 6443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knet-stress
  namespace: service-a
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: knet-stress
  namespace: service-a
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: knet-stress
  namespace: service-a
subjects:
- kind: ServiceAccount
  name: knet-stress
  namespace: service-a
- kind: ServiceAccount
  name: knet-stress
  namespace: service-b
roleRef:
  kind: Role
  name: knet-stress
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knet-stress
  namespace: service-a
  labels:
    app: knet-stress
spec:
  selector:
    matchLabels:
      app: knet-stress
  template:
    metadata:
      labels:
        app: knet-stress
    spec:
      serviceAccountName: knet-stress
      containers:
      - args:
        - --connection-rate=5s
        - --destination=https://knet-stress.service-b:6443/hello
        - --key=/tls/tls.key
        - --cert=/tls/tls.crt
        - --ca=/tls/ca.crt
        image: gcr.io/jetstack-josh/knet-stress:cli
        imagePullPolicy: Always
        name: knet-stress
        ports:
        - containerPort: 6433
          protocol: TCP
          name: web
        volumeMounts:
          - name: tls
            mountPath: /tls
            readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: knet-stress-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: knet-stress
  namespace: service-a
spec:
  duration: 10h
  renewBefore: 5h
  secretName: knet-stress-tls
  dnsNames:
  - knet-stress.service-a
  usages:
    - server auth
    - client auth
  issuerRef:
    name: vault
    kind: Issuer
    group: cert-manager.io
---
apiVersion: v1
kind: Service
metadata:
  name: knet-stress
  namespace: service-b
  labels:
    app: knet-stress
spec:
  selector:
    app: knet-stress
  ports:
    - protocol: TCP
      name: web
      port: 6443
      targetPort: 6443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knet-stress
  namespace: service-b
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: knet-stress
  namespace: service-b
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: knet-stress
  namespace: service-b
subjects:
- kind: ServiceAccount
  name: knet-stress
  namespace: service-a
- kind: ServiceAccount
  name: knet-stress
  namespace: service-b
roleRef:
  kind: Role
  name: knet-stress
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knet-stress
  namespace: service-b
  labels:
    app: knet-stress
spec:
  selector:
    matchLabels:
      app: knet-stress
  template:
    metadata:
      labels:
        app: knet-stress
    spec:
      serviceAccountName: knet-stress
      containers:
      - args:
        - --connection-rate=5s
        - --destination=https://knet-stress.service-a:6443/hello
        - --key=/tls/tls.key
        - --cert=/tls/tls.crt
        - --ca=/tls/ca.crt
        image: gcr.io/jetstack-josh/knet-stress:cli
        imagePullPolicy: Always
        name: knet-stress
        ports:
        - containerPort: 6433
          protocol: TCP
          name: web
        volumeMounts:
          - name: tls
            mountPath: /tls
            readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: knet-stress-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: knet-stress
  namespace: service-b
spec:
  duration: 10h
  renewBefore: 5h
  secretName: knet-stress-tls
  dnsNames:
  - knet-stress.service-b
  usages:
    - server auth
    - client auth
  issuerRef:
    name: vault
    kind: Issuer
    group: cert-manager.io
