apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-issuer
  namespace: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oidc-issuer
  name: oidc-issuer
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-issuer
  template:
    metadata:
      labels:
        app: oidc-issuer
    spec:
      serviceAccountName: oidc-issuer
      containers:
      - image: "gcr.io/jetstack-cre/kube-oidc-proxy/oidc-issuer-linux:v0.3.0"
        ports:
        - containerPort: 6443
        name: oidc-issuer
        command: ["oidc-issuer"]
        args:
          - "--secure-port=6443"
          - "--issuer-url=https://oidc-issuer.auth:6443"
          - "--tls-cert-file=/tls/crt.pem"
          - "--tls-private-key-file=/tls/key.pem"
        volumeMounts:
          - name: tls
            mountPath: /tls
            readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: oidc-issuer-tls
            items:
            - key: tls.crt
              path: crt.pem
            - key: tls.key
              path: key.pem
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: oidc-issuer
  name: oidc-issuer
  namespace: auth
spec:
  ports:
  - port: 6443
    protocol: TCP
    targetPort: 6443
  type: ClusterIP
  selector:
    app: oidc-issuer
