---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-create-delete
  namespace: ping
rules:
- apiGroups: ["", "extensions", "apps", "cert-manager.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alice
  namespace: ping
subjects:
- kind: User
  name: alice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-create-delete
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-create-delete
  namespace: pong
rules:
- apiGroups: ["", "extensions", "apps", "cert-manager.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob
  namespace: pong
subjects:
- kind: User
  name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-create-delete
