apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: service-a
  namespace: service-a
spec:
  duration: 10h
  renewBefore: 5h
  secretName: service-a-tls
  dnsNames:
  - service-a.service-a
  usages:
    - server auth
  issuerRef:
    name: vault
    kind: Issuer
    group: cert-manager.io
