apiVersion: v1
kind: Namespace
metadata:
  name: service-b
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: service-b
  namespace: service-b
spec:
  duration: 10h
  renewBefore: 5h
  secretName: service-b-tls
  dnsNames:
  - service-b.service-b
  usages:
    - server auth
  issuerRef:
    name: vault
    kind: Issuer
    group: cert-manager.io
